language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vitorpavanelli/docker-k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true vitorpavanelli/docker-k8s npm run test
